project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs

website:
  title: Swiss Food Supply
  site-url: https://Thomas-Caspar-Fischer.github.io/hackaton24_17_foodsupply
  navbar:
    logo: resources/logo.svg
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: blog.qmd
        text: Blog
  page-footer:
    border: false
    left: © 2024, Bundesamt für wirtschaftliche Landesversorgung BWL
    right: 
       - icon: github
         href: https://github.com/Thomas-Caspar-Fischer/hackaton24_17_foodsupply
       - icon: envelope-fill
         href: mailto:damian.oswald@protonmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: select
    

lang: de
